### ISSUE TITLE
Missing background files in inputs

### ISSUE THREAD

**Issue by ghost** [Fedrige/Salon_Fryzjerski_Szkola#1]
# Issue Description

There are few mistakes in [css/style.css](https://github.com/Fedrige/Salon_Fryzjerski_Szkola/blob/master/css/style.css) file. 

```css
input:required, textarea:required, select:required {
    background: url(red.png) no-repeat 98%;
}
.contact_form input:required:valid, .contact_form textarea:required:valid, .contact_form select:focus:valid {
    background: url(valid.png) no-repeat 98%;
    box-shadow: 0 0 5px #33dd33;
}

.contact_form input:required:invalid, .contact_form textarea:required:invalid, .contact_form select:focus:invalid {
    background: url(invalid.png) no-repeat 98%;
    box-shadow: 0 0 5px #dd3333;
}
```
"red.png", "valid.png", "invalid.png" are missing.

# Possible solution

Remove unnecessary fragments of code or add missing files.
